### ISSUE TITLE
Dark Mode with a dedicated toggle button

### ISSUE THREAD

**Issue by PandaPrince19** [brainspoof/waves#3]
### **What is this About?**

**Feature Request:**
Addition of dark mode toggle button and storing the users preference in local storage so as to use the same theme that the user has set previously while loading the web app for the next time.

**Expected Result**
The user would be able to toggle between different themes as per their preference

**Current Feature**
There is no such button

**Comment by diganta413** [comment]
Can I work in these issue?

**Comment by unlikefraction** [comment]
> Can I work in these issue?

I'd be very happy if you would.

**Comment by diganta413** [comment]
@brainspoof you can assign this issue to me....I am working on it..
